### ISSUE TITLE
Failing to find some Modelica files with util.searchPath

### ISSUE THREAD

**Issue by AntoineGautier** [lbl-srg/modelica-json#246]
## Classes from MSL

The function `searchPath` from `util.js` fails to find the path to the Modelica files of various types from the MSL.
```js
console.log(process.env.MODELICAPATH) // returns /home/reituag/gitrepo/modelica-buildings:/opt/dymola-2024xRefresh1-x86_64/Modelica/Library/

fs.lstatSync('/opt/dymola-2024xRefresh1-x86_64/Modelica/Library/Modelica 4.0.0/package.mo').isFile() // returns true

utilM2j.searchPath( // returns []
    ['Modelica.Units.SI.Time'], 
    'Buildings.Templates.Plants.Controls.HeatPumps', 
    '/home/reituag/gitrepo/modelica-buildings/Buildings/Templates/Plants/Controls/HeatPumps/AirToWater.mo')

utilM2j.searchPath( // returns []
    ['Modelica.StateGraph.InitialStepWithSignal', 'Modelica.StateGraph.StepWithSignal'], 
    'Buildings.Templates.Plants.Controls.Utilities', 
    '/home/reituag/gitrepo/modelica-buildings/Buildings/Templates/Plants/Controls/Utilities/StageIndex.mo')
```
These types have in common that they are part of packages using the [Single File Mapping](https://specification.modelica.org/maint/3.6/packages.html#mapping-a-package-class-hierarchy-into-a-single-file-nonstructured-entity) rules.

## Classes instantiated using simple names

The class name lookup also fails for some classes from MBL which are instantiated with their [simple name](https://specification.modelica.org/maint/3.6/scoping-name-lookup-and-flattening.html#simple-name-lookup) (not composed using dot notation).

```js
utilM2j.searchPath( // returns [ "/Users/reituag/python/notebooks/js/Enable.mo" ] instead of [ "/home/reituag/gitrepo/modelica-buildings/Buildings/Templates/Plants/Controls/HeatRecoveryChillers/Enable.mo" ]
    ['Enable'], 
    'Buildings.Templates.Plants.Controls.HeatRecoveryChillers', 
    '/home/reituag/gitrepo/modelica-buildings/Buildings/Templates/Plants/Controls/HeatRecoveryChillers/Controller.mo')
```

**Comment by AntoineGautier** [comment]
@anandkp92 Let me know if I can help on this one: it's a blocker for other developments.

**Comment by anandkp92** [comment]
Working on this now [here](https://github.com/lbl-srg/modelica-json/tree/issue246_searchPath)

**Comment by anandkp92** [comment]
@AntoineGautier I believe this is resolved now. If it isn't please reopen and let me know!

**Comment by AntoineGautier** [comment]
@anandkp92 It seems that the issue persists: `searchPath` from `util.js` fails when searching the path of a class that's defined in a [single-file package](https://specification.modelica.org/maint/3.6/packages.html#mapping-a-package-class-hierarchy-into-a-single-file-nonstructured-entity). 
I don't have the rights to reopen the issue but please do.

<img width="988" alt="Image" src="https://github.com/user-attachments/assets/7b29f87c-a4f2-45cf-b8f4-69d15165d7f3" />

**Comment by AntoineGautier** [comment]
@JayHuLBL Still failing on my system. Looking at your MODELICAPATH I believe that the issue comes from the fact that my MSL `package.mo` file is within `/opt/dymola-2025x-x86_64/Modelica/Library/Modelica 4.0.0` (from Dymola install) whereas yours is within `/opt/oct/install/ThirdParty/MSL/MSL400/Modelica` (from OCT install). 
If I create a copy of MSL without the version number in the library root directory name, e.g., `/opt/dymola-2025x-x86_64/Modelica/Library/Modelica` and if MODELICAPATH contains `/opt/dymola-2025x-x86_64/Modelica/Library` then classes from MSL can be found as in your **case.**

Looking at the specification, it is not clear whether a library root in MODELICAPATH suffixed by a whitespace and a version number shall be supported.

Based on https://specification.modelica.org/maint/3.6/packages.html#the-modelica-library-path-modelicapath, clearly not:
> Assume that we want to access the package MyLib.Pack2 (...) Since the name was not found in the top-level scope the search continues in the directories in the MODELICAPATH in the specified order. For the search to succeed, there must be a subdirectory MyLib or a file MyLib.mo in one of the directories mentioned in the MODELICAPATH. If there is no such subdirectory or file, the lookup fails.

Based on https://specification.modelica.org/maint/3.6/packages.html#external-resources, it seems supported for external resources:
> As above for Modelica 3.2.1/package.mo, i.e., resources starting from Modelica 3.2.1, and modelica://Modelica.Mechanics/C.jpg is Modelica 3.2.1/Mechanics/C.jpg – regardless of whether Modelica.Mechanics is stored in Modelica 3.2.1/package.mo, Modelica 3.2.1/Mechanics.mo, or Modelica 3.2.1/Mechanics/package.mo.

I'm tentative to close this issue and add to the documentation of modelica-json that library roots in MODELICAPATH shall exactly match the library names and shall not be suffixed by the library version number.
